name: rukmani
description: "Ecommerce project for Rukmani"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  pin_code_fields: ^8.0.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/apple.svg
    - assets/images/google.svg
    - assets/images/facebook.svg
    - assets/images/back-svgrepo-com.svg
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product_Sans_Bold.ttf
          weight: 700
    - family: Product Sans Medium
      fonts:
        - asset: assets/fonts/Product_Sans_Medium.ttf
          weight: 400
    - family: Product Sans Light
      fonts:
        - asset: assets/fonts/Product_Sans_Light.ttf
          weight: 300
